# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Aggeable

# Model Form Field configuration
form: $/waka/agg/models/aggeable/fields.yaml

# Model Class name
modelClass: Waka\Agg\Models\Aggeable

# Default redirect location
defaultRedirect: waka/agg/aggeables

# Create page
create:
    title: Create Aggeable
    redirect: waka/agg/aggeables/update/:id
    redirectClose: waka/agg/aggeables

# Update page
update:
    title: Edit Aggeable
    redirect: waka/agg/aggeables
    redirectClose: waka/agg/aggeables

# Preview page
preview:
    title: Preview Aggeable
