# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    type:
        label: Type
        scope: tagFilter
        nameFrom: name
        conditions: data_source_id in (:filtered)
        options: 
            '1': Client
            '2': Region

    years:
        label: Année
        type: number
        conditions: ag_year = :filtered
        size: 1
