# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    type:
        label: Type
        modelClass: Waka\utils\Classes\DataSource
        nameFrom: name
        conditions: data_source_id in (:filtered)
        options: 
            '1': Client
            '2': Region

    years:
        label: Année
        type: number
        conditions: ag_year = :filtered
        size: 1

    weeks:
        label: Semaines
        type: number
        conditions: ag_week = :filtered
        size: 1


